from generate_topo import *

if __name__ == "__main__":
    topo = nx.Graph()
    cs_low = 60000
    cs_high = 80000
    bandwidth_low = 400
    bandwidth_high = 800
    fail_rate_low = 0.0
    fail_rate_high = 0.4
    latency_low = 2
    latency_high = 5

    # generate V
    for i in range(42):
        computing_resource = random.randint(cs_low, cs_high)
        fail_rate = random.uniform(fail_rate_low, fail_rate_high)
        topo.add_node(i, computing_resource=computing_resource, fail_rate=fail_rate, active=0, reserved=0, max_sbsfc_index=-1, sbsfcs=set())

    # generate E
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(0, 16, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(0, 3, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(0, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(1, 18, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(1, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(2, 33, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(4, 8, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(5, 38, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(6, 18, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(6, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(7, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 38, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 9, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 11, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 16, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 18, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 23, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 24, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 25, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 26, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 27, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(8, 31, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(9, 27, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(10, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(12, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(13, 25, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(14, 16, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(14, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(15, 16, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(15, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(16, 27, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(16, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(17, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 32, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 33, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 41, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 40, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 25, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 27, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(18, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(19, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(20, 23, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(21, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(22, 25, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(22, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(23, 28, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(23, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(25, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(25, 27, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(27, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(27, 30, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(28, 38, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(28, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(28, 29, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(32, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(33, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(34, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(35, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(36, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(37, 38, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(38, 39, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(39, 41, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())
    bandwidth = random.randint(bandwidth_low, bandwidth_high)
    latency = random.uniform(latency_low, latency_high)
    topo.add_edge(39, 40, bandwidth=bandwidth, active=0, reserved=0, latency=latency, max_sbsfc_index=-1, sbsfcs_s2c=set(), sbsfcs_c2d=set())

    if load_model:
        with open(model_file_name, 'wb') as f:  # open file with write-mode
            sfc_list = generate_sfc_list(topo, process_capacity, size=sfc_size, duration=duration, jitter=jitter)
            nx.draw(topo)
            show()
            model = Model(topo=topo, sfc_list=sfc_list)
            model_string = pickle.dump(model, f)  # serialize and save object
    else:
        with open(topo_file_name, 'wb') as f:  # open file with write-mode
            nx.draw(topo)
            show()
            topo_string = pickle.dump(topo, f)  # serialize and save object

